### ISSUE TITLE
Duplicate theorems

### ISSUE THREAD

**Issue by savask** [metamath/set.mm#2128] opened 2021-08-05 14:17 UTC
In a recent pull request #2087 a pair of duplicate theorems was found, so I decided to run an automated tool to hunt for such examples. Because of the way my program works, the following list is definitely not comprehensive, but I hope it's of some use anyway. Here it is:

- [x] [0mbf](http://us.metamath.org/mpeuni/0mbf.html) in a mathbox of @Achaemenid and [mbf0](http://us.metamath.org/mpeuni/mbf0.html) in a mathbox of @glacode 
- [x] [issmfltle](http://us.metamath.org/mpeuni/issmfltle.html) and [smfpreimale](http://us.metamath.org/mpeuni/smfpreimale.html) both in a mathbox of @glacode
- [x] [mblvon](http://us.metamath.org/mpeuni/mblvon.html) and [vonval2](http://us.metamath.org/mpeuni/vonval2.html) both in a mathbox of @glacode
- [x] [rabeq2i](http://us.metamath.org/mpeuni/rabeq2i.html) in main by @nmegill and [rabid3](http://us.metamath.org/mpeuni/rabid3.html) in a mathbox of @glacode
- [x] [ge0nemnf2](http://us.metamath.org/mpeuni/ge0nemnf2.html) in a mathbox of @glacode and [xrge0neqmnf](http://us.metamath.org/mpeuni/xrge0neqmnf.html) in main by @tirix
- [x] [oddm1d2](http://us.metamath.org/mpeuni/oddm1d2.html) and [zoddb](http://us.metamath.org/mpeuni/zoddb.html) both in main by @avekens
- [x] [snunioo2](http://us.metamath.org/mpeuni/snunioo2.html) in a mathbox by @glacode and [ioounsn](http://us.metamath.org/mpeuni/ioounsn.html) in a mathbox by @TjWhale
- [x] [mptss](http://us.metamath.org/mpeuni/mptss.html) in a mathbox by @glacode and [fmptss](http://us.metamath.org/mpeuni/fmptss.html) in a mathbox by @tirix

In the following cases a newer version was moved to the main part, while the "original" stayed in a mathbox:
- [x] [complss](http://us.metamath.org/mpeuni/complss.html) in main by @benjub and [conss34](http://us.metamath.org/mpeuni/conss34.html) in a mathbox by Andrew Salmon
- [x] [sbeqalbi](http://us.metamath.org/mpeuni/sbeqalbi.html) in a mathbox by Andrew Salmon and [equvelv](http://us.metamath.org/mpeuni/equvelv.html) in main by @wlammen
- [x] [mptex2](http://us.metamath.org/mpeuni/mptex2.html) in main by @glacode and [fvmptelrn](http://us.metamath.org/mpeuni/fvmptelrn.html) by @digama0
- [x] [fmptd2](http://us.metamath.org/mpeuni/fmptd2.html) in a mathbox by @glacode and [fmpttd](http://us.metamath.org/mpeuni/fmpttd.html) in main by @benjub
- [x] [nfbiit](http://us.metamath.org/mpeuni/nfbiit.html) in main by @benjub and [nfbii2](http://us.metamath.org/mpeuni/nfbii2.html) in a mathbox by @giomasce 

These have a 1 step proof, where one theorem references the other (probably a product of minimization):
- [x] [cusgrasizeindslem1](http://us.metamath.org/mpeuni/cusgrasizeindslem1.html) and [usgrafilem1](http://us.metamath.org/mpeuni/usgrafilem1.html) both in main by @avekens
- [x] [fnvinran](http://us.metamath.org/mpeuni/fnvinran.html) in a mathbox by @glacode and [ffvelrnda](http://us.metamath.org/mpeuni/ffvelrnda.html) in main by @digama0
- [x] [tendospid](http://us.metamath.org/mpeuni/tendospid.html) and [fvresi](http://us.metamath.org/mpeuni/fvresi.html) one in main and one in a mathbox by @nmegill
- [x] [rdr](http://us.metamath.org/mpeuni/rdr.html) in a mathbox by Jeff Madsen and [moddiffl](http://us.metamath.org/mpeuni/moddiffl.html) in main by @digama0
- [x] [ifcli](http://us.metamath.org/mpeuni/ifcli.html) in a mathbox by @glacode and [keepel](http://us.metamath.org/mpeuni/keepel.html) in main by Norman
- [x] [nanbi1](http://us.metamath.org/mpeuni/nanbi1.html) in main by @sctfn and [nabi1](http://us.metamath.org/mpeuni/nabi1.html) in a mathbox by Anthony Hart
- [x] [nanbi2](http://us.metamath.org/mpeuni/nanbi2.html) in main by @sctfn and [nabi2](http://us.metamath.org/mpeuni/nabi2.html) in a mathbox by Anthony Hart

Finally, "honorable mentions", theorems which already contain a TODO in their comments:
- [x] [abs3difd](http://us.metamath.org/mpeuni/abs3difd.html) in main by @digama0 and [absnpncand](http://us.metamath.org/mpeuni/absnpncand.html) in a mathbox by @glacode
- [x] [idref](http://us.metamath.org/mpeuni/idref.html) and [issref](http://us.metamath.org/mpeuni/issref.html) both in main by FL
- [x] [tgiooss](http://us.metamath.org/mpeuni/tgiooss.html) in a mathbox by @glacode and [rerest](http://us.metamath.org/mpeuni/rerest.html) in main by @digama0

@nmegill I'm not quite sure what to do with these findings. I'm a bit reluctant to ping all the relevant people, but if it's okay, I could add github names to corresponding theorems in the list (UPDATE: did so). Also some cases probably require special attention, for example, theorem `rdr` contributed in 2010 stayed in the mathbox, while `moddiffl` added in 2016 was moved to the main part and eventually replaced the original proof of `rdr`.

**Comment by nmegill** [comment] 2021-08-05 15:49
Good detective work!

> I'm a bit reluctant to ping all the relevant people, but if it's okay, I could add github names to corresponding theorems in the list.

I think it would be helpful to add github names to your list if it's not too much trouble, along with a notation for "main" or "mathbox" depending on where the theorem is located.

I don't think that we have to notify every contributor, although if someone feels differently speak up.  Just yesterday I added the following to the ~mathbox comment in set.mm that is intended to express our mathbox philosophy:

```
       Mathboxes are provided to help keep your work synchronized with changes
       in set.mm while allowing you to work independently without affecting
       other contributors.  Even though in a sense your mathbox belongs to you,
       it is still part of the shared body of knowledge contained in set.mm,
       and occasionally other people may make maintenance edits to your mathbox
       for things like keeping it synchronized with the rest of set.mm,
       reducing proof lengths, moving your theorems to the main part of set.mm
       when needed, and fixing typos or other errors.  If you want to preserve
       it the way you left it, you can keep a local copy or keep track of the
       GitHub commit number.
```
I think these fall in the category of "maintenance edits".  As a courtesy, we could add a list of @ user names whose mathboxes are affected when we do a cleanup PR for these.  I don't think we need to ask for individual approvals, which would be inefficient (and some contributors may no longer be active anyway).

As for how to fix these, basically common sense should apply.  In general, the contributor with the earlier date should become the official contributor.  If the later contributor duplicated the theorem but with a shorter proof, then the shorter proof should be used and a "(Proof shortened by...)" acknowledgment added.  In all of these cases, the version selected should be moved to the main part of set.mm since it is used in 2 mathboxes.

It can get more complex if the shorter proof invokes earlier theorems in the same mathbox; I guess some judgment calls are needed.

Regardless of whose version is selected and acknowledged, a judgment call will also be needed to choose whose comment is used, if one of them seems better.  We also need to make a judgment call on which label is better/more consistent with our conventions, and in any case the label can be changed to be different from both of them for better consistency.

We should rename the version not selected with an OLD suffix, adding our conventional "Obsolete proof of ~[selected version] as of [date]."  And of course note any label changes or mathbox moves at the top of set.mm as usual.

BTW for theorems in mathboxes, 'show statement [label] /full' will show whose mathbox a theorem is in on the 2nd output line.

**Comment by savask** [comment] 2021-08-06 06:48
>I think it would be helpful to add github names to your list if it's not too much trouble, along with a notation for "main" or "mathbox" depending on where the theorem is located.

I've added github aliases for the contributors I could find on github - it seems that most of relevant people are active set.mm developers, so perhaps everyone can look at their own theorems in the list and take appropriate action.

The list of duplicates is now a task list, so if you resolve some pair of theorems, reference this issue and I'll put a check in front of it.

**Comment by benjub** [comment] 2021-08-06 10:15
As for complss/conss34, I propose to keep the label, comment, and proof of
complss, delete conss34, and modify the credits of complss to "Contributed
by AS... Proof shortened by BJ...".  Can you do it since I won't have
access to my main computer for a few days?

**Comment by nmegill** [comment] 2021-08-06 19:35
For the first item, 0mbf, Brendan Leahy is @Achaemenid

**Comment by tirix** [comment] 2021-08-07 07:37
Concerning `mptss` in a mathbox by @glacode and `fmptss` in a mathbox by @tirix, I believe the theorem shall be moved to the main part of set.mm, since it is used in two different mathboxes. I also believe the theorem to be worth putting in the common part on its own merits!

My proof was done earlier, but Glauco's proof is shorter so it should be kept. You can keep an attribution to me also if you'd like, but I won't mind if I'm not mentionned.

Naming is a good question. For the "mapping to" construct, the definition is `df-mpt`, but there are many theorems which use `fmpt`, like `fmptco`, `fmptsn`, `fmptpr`, `fmpt2`, `fmpti`, `fmptap`, and their variants. I've been using `fmpt` throughout but the page on label conventions lists `mpt` as the abbreviation, so maybe we shall start phasing out `fmpt`? In which case Glauco's name (`mptss`) is also the better one (I had `fmptss`).

I might be able to do the move in the coming two weeks, if there is an agreement.

**Comment by savask** [comment] 2021-08-07 09:15
>I might be able to do the move in the coming two weeks, if there is an agreement.

Most of the duplicates stayed in the database for years, so I guess it can wait a few weeks for sure :-) I hope that corresponding authors will eventually "fix" their own theorems, and in the end someone (maybe me) will make only a small change regarding theorems whose authors don't use github often (like FL, for instance).

**Comment by avekens** [comment] 2021-08-07 10:28
> Naming is a good question. For the "mapping to" construct, the definition is `df-mpt`, but there are many theorems which use `fmpt`, like `fmptco`, `fmptsn`, `fmptpr`, `fmpt2`, `fmpti`, `fmptap`, and their variants. I've been using `fmpt` throughout but the page on label conventions lists `mpt` as the abbreviation, so maybe we shall start phasing out `fmpt`? In which case Glauco's name (`mptss`) is also the better one (I had `fmptss`).

I agree with @tirix that the names should be aligned. But we must be careful: if a function F : A --> B is involved, the "f" is essential and must not be removed (e.g. `fmpti`). Another case is `nfmpt, where `nf`means "not free", so the name must not be changed.

**Comment by glacode** [comment] 2021-08-07 13:01
Hi savask,

useful list. It'b nice to have such technology built into mmj2 or 
Emetamath (warning the author the theorem already exists).

Looking at the dates, I guess in some cases I didn't have my local 
set.mm up to date (I know, "update early"...)

A couple of questions about disj var constraints handling:

- if I'm not mistaken, issmfltle and smfpreimale are not duplicate: 
smfpreimale has strictly less dv constraints, so it is "better". Is your 
tool supposed to highlight these cases?
Recently I've begun writing an outer wrapper just to minimize dv 
constraints (when the theorem is "complex" enough to deserve such outer 
wrapper). I'm afraid your tool would consider all of those as duplicates 
(but one would be a lemma for the other one)

- fmptss has an additional dummy variable constraint w.r.t. mptss (but I 
completely agree that only one of the two should be kept). Are we going 
to consider duplicate theorems even if they differ in dummy var constraints?

Thanks again for the useful list, I will spend some PRs to clean up 
those duplicates.

Glauco

**Comment by glacode** [comment] 2021-08-07 13:08
I completely agree with @tirix

The attribution should go to Thierry who did it first (may be a Revised 
By if you wish to keep my proof, I don't mind).

Glauco

**Comment by savask** [comment] 2021-08-07 14:31
>if I'm not mistaken, issmfltle and smfpreimale are not duplicate: smfpreimale has strictly less dv constraints, so it is "better". Is your tool supposed to highlight these cases?

>fmptss has an additional dummy variable constraint w.r.t. mptss (but I completely agree that only one of the two should be kept). Are we going to consider duplicate theorems even if they differ in dummy var constraints?

Perhaps "duplicate" was a bad word, but the idea was to detect theorems which are either identical to or are weaker than already existing theorems. In my program I completely ignored disjoint variable restrictions, hence it did detect those cases.

Just for your interest (and boasting purposes :-) ), I'll describe the algorithm. First I rename variables in the theorem conclusion, say, something like `( B -> ( A -> B ) )` will turn into `( 1 -> ( 2 -> 1 ) )`, and group theorems with the same conclusion. That way there are too many false positives, so I also compare sorted lists of constants from theorem hypotheses and remove theorems which use only propositional symbols in the conclusion - that way we are left with 408 "duplicate" theorem groups. Then I remove groups which contain more than two theorems (so groups like `cgr3swap12`, `cgr3swap13`, `cgr3rotr`, `trgcgrcom`, `cgr3swap23`, `cgr3rotl` disappear), and also remove theorem pairs which have small edit distance (to remove sequences of lemmata such as `dalem59` and `dalem58`) or "bad" names (with `ax`, `OLD`, etc in them). That gave me a list of 101 potential duplicates which I then went through somewhat sloppily by hand, and ended up with 17 pairs you see in the issue.

So speaking of the way how to prevent it in the future and your comment
>It'b nice to have such technology built into mmj2 or Emetamath (warning the author the theorem already exists).

I fully agree, but I think that this feature already exists in mmj2 and in Emetamath in some form :-) Built-in unification command should be able to find one step proofs, in particular, it should be able to find all these duplicate pairs, including ones with different disjoint restrictions.

It would be nice to have some sort of one-step-minimize command for metamath though, to be able to perform global duplicate searches more effectively, maybe @nmegill can comment on how easy it is to implement one.

**Comment by nmegill** [comment] 2021-08-07 14:32
@tirix :
> Naming is a good question. For the "mapping to" construct, the definition is `df-mpt`, but there are many theorems which use `fmpt`, like `fmptco`, `fmptsn`, `fmptpr`, `fmpt2`, `fmpti`, `fmptap`, and their variants. I've been using `fmpt` throughout but the page on label conventions lists `mpt` as the abbreviation, so maybe we shall start phasing out `fmpt`? In which case Glauco's name (`mptss`) is also the better one (I had `fmptss`).

I agree with @avekens, "mpt" and not "fmpt" is supposed to be the abbreviation for the maps-to construct.  The theorem ~fmpt combines the two abbrevations "f" and "mpt", relating df-f and df-mpt.  Other uses of "fmpt" should be changed to "mpt" unless df-f is involved (nor in the case of nfmpt\* which combine "nf" and "mpt").

**Comment by glacode** [comment] 2021-08-07 16:09
On 07/08/2021 16:31, savask wrote:
>
>> It'b nice to have such technology built into mmj2 or Emetamath (warning the author the theorem already exists).
> I fully agree, but I think that this feature already exists in mmj2 and in Emetamath in some form :-) Built-in unification command should be able to find one step proofs, in particular, it should be able to find all these duplicate pairs, including ones with different disjoint restrictions.
>

Yes, mmj2 does one-step unification. The problem is that I often start 
from the conclusion and proof backward, and step by step "decide" what 
to select as hypothesis. I believe this approach helps to avoid 
redundant hypothesis.

At the end of the proof, mmj2 doesn't override my proof with the 
one-step unification, thus the duplicate proof is not detected.

Of course, I search for the pre-existing proof upfront, but it looks 
like, sometimes, my search misses it.

As you say, a built-in "minimize" tool would do the job (and it would do 
much more...)

Glauco

**Comment by david-a-wheeler** [comment] 2021-08-09 15:22
@savask - as Norm mentioned, great detective work, thanks for reporting this.

**Comment by benjub** [comment] 2022-08-25 23:45
@wlammen : can you take care of the line
> [sbeqalbi](http://us.metamath.org/mpeuni/sbeqalbi.html) in a mathbox by Andrew Salmon and [equvelv](http://us.metamath.org/mpeuni/equvelv.html) in main by @wlammen

in the initial post above ?

Probably: keep your label, with credits: contrib by AS...; Reduce dependencies... Revised by WL ; Proof shortened by WL, with the three given dates. And deprecate sbeqalbi. Do what you think is best.

**Comment by benjub** [comment] 2022-08-26 10:24
Last remaining line:
> [idref](http://us.metamath.org/mpeuni/idref.html) and [issref](http://us.metamath.org/mpeuni/issref.html) both in main by FL

I propose to deprecate ~issref (which is only used by mathbox theorems) in favor of the much shorter ~idref.  The fact that ~issref can be proved before the introduction of various definitions related to functions (df-fun to df-fv) is not important in my opinion (since definitions are eliminable and conservative anyway).  Do you agree @savask @jkingdon @digama0 @wlammen @avekens ?

**Comment by wlammen** [comment] 2022-08-26 12:13
~ issref makes sense if reflexivity is somehow useful in building up infrastructure around the definition of functions, so it should be there already.  In the past 6 years nobody used ~ issref for this purpose, though.  I looked through set.mm around the date of Norm's revision of 30-Mar-2016 to see what he might have had in mind then.  In April 2016 in Main the only theorem changed and remotely related to ~ issref is ~ predbrg.  I cannot see, how a combination of both can create something useful.

So I vote for keeping ~ idref.

**Comment by jkingdon** [comment] 2022-08-26 13:23
> I propose to deprecate ~issref (which is only used by mathbox theorems) in favor of the much shorter ~idref

Sounds good to me.

**Comment by savask** [comment] 2022-08-26 14:26
>I propose to deprecate ~issref ...

I also agree (as I understand "(Proof modification is discouraged.)" can be removed from ~idref after the change).

**Comment by benjub** [comment] 2022-08-29 22:58
After the discussion at #2802, I kept ~issref as ~idrefALT (with a much shortened proof).
So all 17 tasks are completed. Is there something left to do on that ? Maybe @savask could rerun his script to check that no new duplicates appeared and that all have been treated ? And after that, the issue could be closed.

**Comment by savask** [comment] 2022-09-01 14:31
@benjub
The program outputs way too many false positives, so I have to do aggressive pruning and also churn through the list manually. I did this now and found several new instances (see the first post), but I suggest to close this issue after new duplicates get resolved.

**Comment by benjub** [comment] 2022-09-01 23:23
nfbii2 : should we move it to Main as nfbiitALT, commenting "shorter proof requiring more axioms", or simply remove it ? (I would go for the second option). (**edit**: theorem by @giomasce)

**Comment by giomasce** [comment] 2022-09-02 06:37
My only demand is that a theorem with precisely that form remains in the database, because it is used by `mmpp` to automatically generate proofs. As for which one to choose, I don't have preferences. Thanks!

**Comment by benjub** [comment] 2022-09-02 21:23
All tasks are done. I let @savask close the issue.

**Closed as completed** 2022-09-06 15:21 UTC
