### ISSUE TITLE
Redundancy of ax-cnex

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2137] opened 2021-08-09 01:00 UTC
The comment to http://us.metamath.org/mpeuni/ax-cnex.html claims this axiom is redundant (something which I don't know much about) and that http://us.metamath.org/mpeuni/cnexALT.html demonstrates this (which is either wrong, or I've misinterpreted what the comment is trying to say). What I mean is that the proof of cnexALT relies on ax-cnex, which I assume is some flavor of oversight. Maybe a minimization run (or similar cleanup) went awry or something?

**Comment by digama0** [comment] 2021-08-09 03:30
I think the problem is that rpnnen1lem1 uses qex instead of qexALT. It should probably be marked as proof modification discouraged as well, since it is intended to be used in cnexALT. (There might be more issues that will be revealed once this one is resolved.)

**Comment by jkingdon** [comment] 2021-08-10 20:37
> I think the problem is that rpnnen1lem1 uses qex instead of qexALT. It should probably be marked as proof modification discouraged as well, since it is intended to be used in cnexALT. (There might be more issues that will be revealed once this one is resolved.)

Minimization is not supposed to add axioms, with or without proof modification discouraged, right?

I suppose if we wanted to get fancy we'd have something like a `$j` tag for "axiom ax-foo forbidden in this proof" and tools to check it, but for now we just have a "don't add axioms" practice and tools which try to follow that precept.

**Comment by nmegill** [comment] 2021-08-10 23:53
> > I think the problem is that rpnnen1lem1 uses qex instead of qexALT. It should probably be marked as proof modification discouraged as well, since it is intended to be used in cnexALT. (There might be more issues that will be revealed once this one is resolved.)
> 

Among set.mm backups that I have, qexALT first appears on Aug. 14, 2015.  The proof of rpnnen1lem1 uses it up to and including Jul. 11, 2020.  In the next version I saved, Aug. 2, 2020, the proof started using qex.  So somewhere between those 2 dates it was changed from qexALT to qex for an unknown reason.

In metamath.exe 0.183 30-Jun-2020 we started requiring \*ALTs to have discouragement tags in 'verify markup'.  So around that time there was some \*ALT activity at least to add discouragements.  Maybe it was even my fault when we were cleaning up some \*ALT stuff, but I don't remember this specifically.  There may have been some discussion on the Google group about \*ALTs around that time, although I haven't checked carefully.

Maybe a git guru could do a "blame" or something to pin down the commit that made the change, and see what other things were changed.  BTW the string "fmptd qexALT elmap", later changed to "fmptd qex elmap", uniquely matches the rpnnen1lem1 compressed proof  in all versions.

> Minimization is not supposed to add axioms, with or without proof modification discouraged, right?

Currently, yes.  In older versions, by default it would add axioms, and you had to specify "min ... /no_new_axioms_from ax-\*" to prevent that.  Originally no one cared much about which axioms were used except for a few like ax-ac.  The default was changed to not add new axioms in metamath.exe 0.178 10-Aug-2019, when "/allow_new_axioms" was added.  Now if you want to let it bring in new definitions, you have to specify "min ... /allow_new_axioms /no_new_axioms_from ax-*".

**Comment by savask** [comment] 2021-08-11 05:13
>Maybe a git guru could do a "blame" or something to pin down the commit that made the change, and see what other things were changed

I'm no git guru, but the command `git log --after="2020-07-11" --until="2020-08-2" -S "fmptd qexALT elmap"` points at commit b99f275baaa2bfb0fe02a1c14dfd041f65209d19.

**Comment by nmegill** [comment] 2021-08-11 19:05
It looks like nnexALT and qexALT were changed to nnex and qex in rpnnen1lem1,3,4,5 on Aug. 1, 2020.  This was apparently part of a project to reduce unnecessary uses of \*ALTs (which in this case are necessary).  Could @benjub confirm?

I did verify that in the (good) 2020-07-11 set.mm, cnexALT correctly did not trace back to ax-cnex.

Here are all *ALT from 0cnALT to cnexALT and their uses:

2020-07-11 set.mm:
```
MM> sh us 0cnALT,0reALT,nnexALT,nnindALT,zexALT,nn0indALT,uzind4ALT
,nn0ge2m1nnALT,qexALT,reexALT,cnexALT
Statement "0cnALT" is not referenced in the proof of any statement.
  (None)
Statement "0reALT" is directly referenced in the proof of 1 statement:
  psgnodpmr
Statement "nnexALT" is directly referenced in the proofs of 6 statements:
  zexALT qexALT rpnnen1lem1 rpnnen1lem3 rpnnen1lem4 rpnnen1lem5
Statement "nnindALT" is not referenced in the proof of any statement.
  (None)
Statement "zexALT" is directly referenced in the proof of 1 statement:
  qexALT
Statement "nn0indALT" is directly referenced in the proofs of 3 statements:
  uzaddcl faclbnd4lem4 ipasslem1
Statement "uzind4ALT" is not referenced in the proof of any statement.
  (None)
Statement "nn0ge2m1nnALT" is not referenced in the proof of any statement.
  (None)
Statement "qexALT" is directly referenced in the proofs of 4 statements:
  rpnnen1lem1 rpnnen1lem3 rpnnen1lem4 rpnnen1lem5
Statement "reexALT" is directly referenced in the proof of 1 statement:
  cnexALT
Statement "cnexALT" is not referenced in the proof of any statement.
  (None)
```

2020-08-02 set.mm:
```
MM> sh us 0cnALT,0reALT,nnexALT,nnindALT,zexALT,nn0indALT,uzind4ALT
,nn0ge2m1nnALT,qexALT,reexALT,cnexALT
Statement "0cnALT" is not referenced in the proof of any statement.
  (None)
Statement "0reALT" is directly referenced in the proof of 1 statement:
  psgnodpmr
Statement "nnexALT" is directly referenced in the proofs of 2 statements:
  zexALT qexALT
Statement "nnindALT" is not referenced in the proof of any statement.
  (None)
Statement "zexALT" is directly referenced in the proof of 1 statement:
  qexALT
Statement "nn0indALT" is directly referenced in the proofs of 3 statements:
  uzaddcl faclbnd4lem4 ipasslem1
Statement "uzind4ALT" is not referenced in the proof of any statement.
  (None)
Statement "nn0ge2m1nnALT" is not referenced in the proof of any statement.
  (None)
Statement "qexALT" is not referenced in the proof of any statement.
  (None)
Statement "reexALT" is directly referenced in the proof of 1 statement:
  cnexALT
Statement "cnexALT" is not referenced in the proof of any statement.
  (None)
```

Difference:
```
7,8c7,8
< Statement "nnexALT" is directly referenced in the proofs of 6 statements:
<   zexALT qexALT rpnnen1lem1 rpnnen1lem3 rpnnen1lem4 rpnnen1lem5
---
> Statement "nnexALT" is directly referenced in the proofs of 2 statements:
>   zexALT qexALT
19,20c19,20
< Statement "qexALT" is directly referenced in the proofs of 4 statements:
<   rpnnen1lem1 rpnnen1lem3 rpnnen1lem4 rpnnen1lem5
---
> Statement "qexALT" is not referenced in the proof of any statement.
>   (None)
```

It basically looks like nnex and qex should be restored to nnexALT and qexALT in rpnnen1lem1, rpnnen1lem3, rpnnen1lem4, rpnnen1lem5.  This will probably fix the problem.

A related issue:  in the **OLD** 2020-07-11 set.mm, we also have (note the "/recursive"):
```
MM> sh us nnexALT/recursive
Statement "nnexALT" directly or indirectly affects the proofs of 19 statements:
  zexALT qexALT rpnnen1lem1 rpnnen1lem3 rpnnen1lem4 rpnnen1lem5 rpnnen1 reexALT
  cnexALT rpnnen rexpen cpnnen rucALT cnso 2ndcredom opnreen rectbntr0
  aannenlem3 aannen
```

These uses aren't in the current set.mm, but will reappear when nnexALT, qexALT are restored. 
 My guess would have been that everything after cnexALT are intended to use the non-ALT versions, although rpnnen intrinsically needs rpnnen1lem1,3,4,5, so I'm not sure.  Could @digama0  clarify the intent here?

BTW while 0reALT isn't part of the cnexALT project, I noticed above that psgnodpmr uses 0reALT.  I think it should use 0re instead.

**Comment by digama0** [comment] 2021-08-11 20:00
`rpnnen1` is used in two ways: (1) as the first half of `rpnnen` (which is a "regular" theorem and will be referred to downstream), and (2) as part of the proof of `cnexALT` (so it needs to use `*ALT` versions of `nnex` and `qex`). As a result, uses of `nnexALT` will naturally escape to regular theorems, and I don't think this is a problem, unless you are interested in eliminating uses of the replacement axiom (since the proof of `cnexALT` trades `ax-rep` for `ax-cnex`). If we want to separate these two uses of  `rpnnen1`, it can be proven with `|- QQ e. _V` as a hypothesis, and then you can use `qex` in `rpnnen` and `qexALT` in `cnexALT`.

**Comment by benjub** [comment] 2021-08-11 20:49
My bad, the theorem did not have the proof modification tag so I removed
discouraged statements from its proof without further look.  I hope there
were no other problems with that PR.


Le mer. 11 août 2021 à 22:01, Mario Carneiro ***@***.***> a
écrit :

**Comment by digama0** [comment] 2021-08-11 21:13
I believe the theorem itself predates the introduction of proof modification tags, so I think it's understandable why this all happened. In any case it should be easy to fix and prevent a re-occurrence.

**Comment by nmegill** [comment] 2021-08-12 01:14
> If we want to separate these two uses of `rpnnen1`, it can be proven with `|- QQ e. _V` as a hypothesis, and then you can use `qex` in `rpnnen` and `qexALT` in `cnexALT`.

We would also need to add  `|- NN e. _V` as a hypothesis.  Anyway, I like that idea, which would let us cleanly separate the nnex/qex and nnexALT/qexALT uses with no additional lemmas and very little additional overhead in set.mm.  It also would mean that we won't need to add discouragement tags to rpnnen1 and its lemmas.

**Comment by digama0** [comment] 2021-08-12 01:16
>  It also would mean that we won't need to add discouragement tags to rpnnen1 and its lemmas.

No, we would still need to protect the theorem, or else some later optimization would just use `qex` instead of the hypothesis.

**Comment by nmegill** [comment] 2021-08-12 02:29
> > It also would mean that we won't need to add discouragement tags to rpnnen1 and its lemmas.
> 
> No, we would still need to protect the theorem, or else some later optimization would just use `qex` instead of the hypothesis.

'minimize' won't do that because bringing in either qex or qexALT would add new axioms.  Manual changes to shorten a proof without adding new axiom dependencies (which should be checked by anyone manually shortening a proof) are normally welcome, and unnecessary proof modification discouragements would discourage that.

But if it feels safer to add discouragements in this special case, I'm fine with that.

**Comment by nmegill** [comment] 2021-08-13 15:34
I will make these changes in the next few days.

**Closed as completed** 2021-08-13 21:03 UTC
