### ISSUE TITLE
Missing warnings from Travis; verify markup's /date_skip fails

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#794] opened 2019-03-23 15:40 UTC
See:
https://github.com/metamath/set.mm/pull/792#issuecomment-475879549

**Comment by david-a-wheeler** [comment] 2019-03-23 18:52
@nmegill  @avekens - Something is wrong with the latest metamath code for verifying comments in databases, specifically the option "/date_skip" in "verify markup" doesn't work.

Running with the current set.mm commit 3106c83fd6f00adce38e5fc65bf82a47e5651824 :

~~~~
$ metamath set.mm
Metamath - Version 0.175 8-Mar-2019           Type HELP for help, EXIT to exit.
MM> READ "set.mm"
Reading source file "set.mm"... 34213976 bytes
34213976 bytes were read into the source buffer.
The source has 154618 statements; 2224 are $a and 32192 are $p.
No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
if you want to check them.
MM> verify markup *
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
?Warning:  There is no "(Contributed by...)" in the comment above statement
    154561, label "f1otrgds".
?Warning:  There is no "(Contributed by...)" in the comment above statement
    154563, label "f1otrgitv".
?Warning:  There is no "(Contributed by...)" in the comment above statement
    154565, label "f1otrg".
Checking section header comments...
Checking bibliographic references...
MM> verify markup * /date_skip
Checking statement label conventions...
Checking latexdef, htmldef, althtmldef...
Checking statement comments...
Checking section header comments...
Checking bibliographic references...
No errors were found.
MM>
~~~~

**Comment by tirix** [comment] 2019-03-23 18:53
If it helps, I also noticed that my commit [63a2999](https://github.com/metamath/set.mm/pull/793/commits/63a29997f045b6e6012c82d882f377be9bbd5d50) in pull request #793 missed one coma between contributor and date for the ` tgcgrtriv ` statement, but this was not detected by the travis build.

**Comment by nmegill** [comment] 2019-03-23 19:32
@david-a-wheeler You are right - stupid me, I completely overlooked the /date_skip in my tests.  None are so blind as those who will not see...

The code that /date_skip skips was originally intended to make sure "Contributed by" comes before "Revised by" etc., and as a side-effect checks that "Contributed by" is there in the first place.  So the "Contributed by" check is indeed no longer being done in Travis.

The current purpose of /date_skip in your script is a workaround to ignore the date at the top of set.mm, which has been the cause of many merge conflicts, but unfortunately it bypasses other important date-related checks as well.

Let me think about how to address it.  Probably I will add "/top_date_skip" to skip only the top date check, so that all other date-related checks will start to be done again.  Then we can modify your script to use /top_date_skip.  For now, let us continue to use /date_skip until I do that in the next couple of days.

Thanks for your help!

Norm

**Comment by david-a-wheeler** [comment] 2019-03-23 19:35
@nmegill - happy to help.  /top_date_skip sounds like a good solution.

**Comment by david-a-wheeler** [comment] 2019-03-23 19:36
No problem, and no magic.  Once I could reproduce the problem I just debugged the ordinary way, executing a binary search until I found what caused the unexpected result.

**Comment by nmegill** [comment] 2019-03-25 06:43
I added '/top_date_skip' to 'verify markup' in metamath.exe and updated the Travis scripts.  This should close the issue.

**Closed by nmegill** 2019-03-25 06:43 UTC
